Update for secure codec support
linaro-home/clearkeydrmplugin pull request #2
Opened 2018-05-04 02:12 UTC by KenLSoft

Hi,
This PR contains 5 commit to support real secure codec support.
clearkeydrmplugin now requires secure codec;
and created a standalone Aes decryptor for secure decrypt since there are many difference with original decryptor.
Rest commits are tiny to fix some warnings.

2018-06-21 15:14 UTC, petegriffin requested changes
Hi Ken,

Many thanks for your patches, and sorry for the delay in reviewing this pull request. I like the optimization of avoiding a REE to secure world transition for the clear data, and also of creating a new secure decryptor class.

As part of this work can you also update the unit test code in clearkeydrmplugin/tests/AesCtrDecryptorUnittest.cpp to instantiate a AesCtrDecryptorSecure class, and ensure those tests still pass.

Note for Android we aren't using the copy of this code which is also found in optee-clearkey-cdmi/tests directory.

2018-06-21 15:14 UTC, petegriffin commented on Android.mk
> +USE_TEE_SDP ?= fasle
This should be CFG_SECURE_DATA_PATH to keep it consistent with other TA's like Playready (also it follows OP-TEE's nomenclature.

I think you can also make generating the secureDecryptor dependent on this flag

2018-06-21 15:14 UTC, petegriffin commented on AesCtrDecryptorSecure.cpp
> +        Iv opensslIv;
We can remove the references to openssl here

2018-06-21 15:14 UTC, petegriffin commented on Android.mk
> +USE_TEE_SDP ?= false
To be consistent with other TA's and also OP-TEE nomenclature we should enable this based on CFG_SECURE_DATA_PATH

2018-06-21 15:14 UTC, petegriffin commented on CryptoPlugin.cpp
> +#elif USE_TEE_SDP==true
CFG_SECURE_DATA_PATH please

2018-06-21 15:14 UTC, petegriffin commented on CryptoPlugin.h
> +#if USE_TEE_SDP==true
CFG_SECURE_DATA_PATH please

2018-06-27 07:47 UTC, KenLSoft commented
Will update.

2018-06-28 10:53 UTC, KenLSoft commented
Sorry I got some mis-operations. New patchsets below this comment would be the latest one.

For the test -- I can not find a good solution for the test since memory is protected by hardware ; and I need to remove the protection to check if result is correct; so I will leave test app later.

Other comments are all updated.

2018-07-03 16:47 UTC, petegriffin commented
Hi Ken,

Thanks for the changes so far.

With regards to the test app and testing secure decryptor class. If you make the changes to instantiate the class and allocate a buffer from ION. I can test it on iMX8M-evk board as that platform has secure codecs support and I can disable the memory protection in ATF.

2018-07-09 19:10 UTC, ajutras-linaro requested changes

2018-07-09 19:10 UTC, ajutras-linaro commented on Android.mk
> +CFG_SECURE_DATA_PATH ?= fasle
To be consistent with other usages of CFG_SECURE_DATA_PATH within Linaro, this line should be:

+CFG_SECURE_DATA_PATH ?= n

To enable SDP, someone needs to export:

export CFG_SECURE_DATA_PATH=y

Otherwise, typo 'fasle' vs 'false'.

2018-07-09 19:10 UTC, ajutras-linaro commented on CryptoPlugin.h
> +#if CFG_SECURE_DATA_PATH==true
To also be consistent with other usages of CFG_SECURE_DATA_PATH within Linaro, CFG_SECURE_DATA_PATH would only be defined when it is enabled. At this line, #ifdef CFG_SECURE_DATA_PATH would be used.

2018-07-16 07:57 UTC, KenLSoft commented
Thanks for reviewing.
@petegriffin I tried to write the test but seeems I need to call platform APIs for secure buffer allocating instead of an output buffer in stack; which means needs some code change for it; so I planned to create another PR for the test. What's your option? Thanks.

2018-07-31 22:08 UTC, petegriffin commented
Hi Ken,

Sorry for the long delay between in replies. I'm actually on parental leave atm (OoO July & August). It would be preferable to update the unitary test code at the same time as adding the new secure decryptor class so we can be sure we've not introduced any regressions.

2018-08-07 05:04 UTC, KenLSoft commented
OK.
And since I am fully occupied these days so that my response won't be that quick, sorry for that.

2018-08-09 14:10 UTC, petegriffin commented
Hi Ken,

I just thought..I think you could pretty much re-use the ion implementation Alex did here https://github.com/linaro-mmwg/open-content-decryption-module/commit/1a8870e93ba4e83a72424478ec05b2882cae4753 and add it to the unit test code to allocate the secure buffer.

2018-08-12 07:13 UTC, KenLSoft commented
Ah. that code is useful; is it ok to copy one or two files from that project?

2018-08-14 09:19 UTC, petegriffin commented
Yes it is Linaro written code, so we can re-use it here

2018-08-20 19:05 UTC, ajutras-linaro approved these changes

2018-08-20 19:13 UTC, ajutras-linaro commented
The changes look good to me.

2018-08-21 15:22 UTC, petegriffin approved these changes

2018-08-21 15:23 UTC, merged

2018-08-21 15:23 UTC, petegriffin commented
LGTM